---
image: docker:latest
stages:
  - build

job:
  stage: build
  tags:
    - docker
  script:
    - docker login -u $CI_ARTI_USER -p $CI_ARTI_PASS -e team@typhon.com https://$CI_ARTI_URL
    - docker build -t ${CI_ARTI_URL}:jessie-puppet410 .
    - docker push https://${CI_ARTI_URL}:jessie-puppet410 .

