---
stages:
  - build

job:
  stage: build
  tags:
    - docker
  script:
    - env
    - docker login -u $CI_ARTI_USER -p $CI_ARTI_PASS https://$CI_ARTI_URL
    - docker build -t ${CI_ARTI_URL}/typhonteam:jessie-ruby22-puppet410 .
    - docker push ${CI_ARTI_URL}/typhonteam:jessie-ruby22-puppet410

